# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55cbe1ed14f4c31660e41a50a7e31d7b87f9001aa0c51ed15d6052155873ca41bbcf4581f0ae7fe88bab38a3bfadba215e123476d0eb63c32105da85033d9433

test:
  secret_key_base: 84cf047519dd8411d3e821594079852dbb8aef29e4a5f2ab59f2c744d4e95baf4de5fb897f74c9a48f34ca68a07d8747c659b045cb6e0a8799d0c84a776f9e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
